"""Refactoring

Revision ID: 247bdec4dcf2
Revises: bfaa07bc5b0f
Create Date: 2024-10-15 22:36:17.773622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '247bdec4dcf2'
down_revision: Union[str, None] = 'bfaa07bc5b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fact_procedure', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_picture', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('profile_picture', 'picture_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('profile_picture', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('profile_picture', 'master',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('recommended_procedure', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('user_email_key', 'user', type_='unique')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.alter_column('visit', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visit', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_unique_constraint('user_email_key', 'user', ['email'])
    op.alter_column('user', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'registered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('recommended_procedure', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile_picture', 'master',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('profile_picture', 'upload_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('profile_picture', 'picture_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('profile_picture', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('profile', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('fact_procedure', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
