"""Add registered at to clinic

Revision ID: 52afe30a5eaf
Revises: e0ee3cc96e8d
Create Date: 2024-10-26 18:05:09.583579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52afe30a5eaf'
down_revision: Union[str, None] = 'e0ee3cc96e8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('сlinic', sa.Column('registered_at', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('сlinic', 'registered_at')
    # ### end Alembic commands ###
