"""Remove pfofile_picture_url and set master fields

Revision ID: e0614689de10
Revises: a0928cc47c93
Create Date: 2024-10-01 20:47:43.762318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0614689de10'
down_revision: Union[str, None] = 'a0928cc47c93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'profile_picture_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('profile_picture_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
