"""Add clinic user table

Revision ID: e0ee3cc96e8d
Revises: 760e5aa4fc0f
Create Date: 2024-10-24 23:53:34.970092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0ee3cc96e8d'
down_revision: Union[str, None] = '760e5aa4fc0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('сlinic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('inn', sa.Integer(), nullable=False),
    sa.Column('organisation_name', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inn'),
    sa.UniqueConstraint('organisation_name'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_сlinic_email'), 'сlinic', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_сlinic_email'), table_name='сlinic')
    op.drop_table('сlinic')
    # ### end Alembic commands ###
