"""Set master to profile_picture

Revision ID: e96f0673a8c6
Revises: e0614689de10
Create Date: 2024-10-01 20:59:45.516779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96f0673a8c6'
down_revision: Union[str, None] = 'e0614689de10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_picture', sa.Column('master', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile_picture', 'master')
    # ### end Alembic commands ###
